---
language: python
services: docker

env:
  global:
    - ROLE_NAME: ansible-role-cron
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker

script:
  # Run tests.
  - molecule test

notifications:
  email: false
